spring.application.name=gestorclinia

#CONFIG POOL CONNEXION
spring.datasource.hikari.minimumIdle=5
spring.datasource.hikari.maximumPoolSize=20
spring.datasource.hikari.idleTimeout=30000
spring.datasource.hikari.maxLifetime=2000000
spring.datasource.hikari.connectionTimeout=30000
spring.datasource.hikari.poolName=Poolbydata
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/mydblogin
spring.datasource.username=postgres
spring.datasource.password=edding350
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

twilio.account.sid=${TWILIO_ACCOUNT}
twilio.auth.token=${TWILIO_TOKEN}
twilio.phone.number=${TWILIO_PHONE}

jwt.secret.key=${JWT_SECRET_KEY}
jwt.time.expiration=360000000
jwt.time.refresh=604800000

spring.graphql.graphiql.enabled=true