spring.application.name=gestorclinia

#CONFIG POOL CONNEXION
spring.datasource.hikari.minimumIdle=5
spring.datasource.hikari.maximumPoolSize=20
spring.datasource.hikari.idleTimeout=30000
spring.datasource.hikari.maxLifetime=2000000
spring.datasource.hikari.connectionTimeout=30000
spring.datasource.hikari.poolName=Poolbydata
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/mydblogin
spring.datasource.username=postgres
spring.datasource.password=edding350
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret.key=32a812ae37325ef1ecb0470f7205e7fdcb038aacef44ad631fdc9186179de32c
jwt.time.expiration=3600000
jwt.time.refresh=604800000


